import Image from "next/image";

export const HowWorks = () => {
  return (
    <>
      <div className="hero pt-20 w-full mt-10">
        <div className="mx-auto max-w-screen-lg px-12 flex flex-col lg:flex-col justify-items-start w-90">
          <div>
            <h1 className="text-5xl text-bold text-center">How it works?</h1>
          </div>
          <div>
            <h3 className="text-2xl mt-4 text-center">
              Write what you need, a template will be generated:
            </h3>
          </div>
        </div>
      </div>
      <div className="hero pt-20">
        <div className="hero-content flex-col lg:flex-row w-screen flex-col space-y-10">
        <div className="flex flex-row w-full ">
          <Image
            src="/images/start_building_api_2x.webp"
            alt="imagen_api"
            width={514}
            height={341}
            className="max-w-lg mx-auto"
            layout="responsive"
          />
        </div>
        <div className="flex flex-row w-full mx-auto">
          <ul className="mx-auto">
            <li className="mb-4">
                <div className="flex flex-row space-x-3">
                  <Image
                    src="/images/bullet.webp"
                    width={32}
                    height={32}
                    alt="icon list"
                  />
                  <h3 className="text-2xl">Slides, emails, tweets...</h3>
                </div>
              </li>
              <li className="mb-4">
                <div className="flex flex-row space-x-3">
                  <Image
                    src="/images/bullet.webp"
                    width={32}
                    height={32}
                    alt="icon list"
                  />
                  <h3 className="text-2xl">Prompt what you need!</h3>
                </div>
              </li>
              <li className="mb-4">
                <div className="flex flex-row space-x-3">
                  <Image
                    src="/images/bullet.webp"
                    width={32}
                    height={32}
                    alt="icon list"
                  />
                  <h3 className="text-2xl">Generated by AI</h3>
                </div>
              </li>
              <li className="mb-4">
                <div className="flex flex-row space-x-3">
                  <Image
                    src="/images/bullet.webp"
                    width={32}
                    height={32}
                    alt="icon list"
                  />
                  <h3 className="text-2xl">Download or copy/paste it</h3>
                </div>
              </li>
              <li className="mb-4">
                <div className="flex flex-row space-x-3">
                  <Image
                    src="/images/bullet.webp"
                    width={32}
                    height={32}
                    alt="icon list"
                    className="max-w-xs"
                  />
                  <h3 className="text-2xl">
                    All the times you need
                  </h3>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </>
  );
};
